#ifndef CRML_FEEDBACK_H
#define CRML_FEEDBACK_H
#include <stdint.h>
#define CRML_FEEDBACK_INFO 0u
#define CRML_FEEDBACK_SUCCESS 1u
#define CRML_FEEDBACK_WARNING 2u
#define CRML_FEEDBACK_ERROR 3u
#define CRML_FEEDBACK_QUEUED 1
#define CRML_FEEDBACK_PRESENTED 2
#define CRML_FEEDBACK_EXPIRED_UNPRESENTED 3
#define CRML_FEEDBACK_EXPIRED_PRESENTED 4
#define CRML_FEEDBACK_DISMISSED 5
#define CRML_FEEDBACK_CANCELLED 6
#define CRML_FEEDBACK_TEXT_MAX 240u
#endif
